### ISSUE TITLE
Build problem with autoconf 2.70

### ISSUE THREAD

**Issue by akobel** [robol/MPSolve#27]
Hi,
compilation from git source breaks with autoconf 2.70. (Noticed in the arch package at [https://aur.archlinux.org/packages/mpsolve-git/](https://aur.archlinux.org/packages/mpsolve-git/)). autogen.sh just throws some warnings, but configure breaks completely down the road.

I'm not well-versed with autoconf, unfortunately, and couldn't find a quick fix. I'm attaching the [configure script](https://github.com/robol/MPSolve/files/5811415/configure.zip) created on my machine by autoconf 2.70 in the hope that it can help. The error reported is:
```
./configure: line 21675: syntax error near unexpected token `newline'
./configure: line 21675: `    '''
```
and indeed that line looks fishy, but I have no clue how and why autoconf created it...

For what it's worth, the release tarball of 3.2.1 builds perfectly on that system. Reverting to autoconf 2.69 helps, too.

**Comment by robol** [comment]
Thanks for reporting this. I had a quick look and it looks like these tests are part of the "standard" compiler detection stuff. I have no idea why autoconf would generate this broken script. 

I see from the changelog that autoconf 2.70 is not perfectly backward compatible with 2.69. I will see if I manage to create a configure script that works with both.

**Comment by jkyang92** [comment]
I just encountered this building Macaulay2, and found a potential fix. I believes on line 516-527 of `configure.ac` there needs to be one more level of brackets. In particular, the following code, with an extra layer of brackets around the call to `AC_PATH_PROGS_FEATURE_CHECK` works for me

```
AC_CACHE_CHECK([for a valid mex compiler], [ac_cv_path_MEX],
    [AC_PATH_PROGS_FEATURE_CHECK([MEX], [mex], 
    [[
      mex_is_matlab_output=`$ac_path_MEX -help 2>&1 | grep "MATLAB\|mkoctfile"`
      mex_is_matlab_retcode=$?
      if [[ "$mex_is_matlab_retcode" != "0" ]]; then
	 MEX=""
      else
         ac_cv_path_MEX=$ac_path_MEX
	 MEX=$ac_path_MEX
      fi
      ]])])
```

I'm not exactly fluent in autoconf but it seems that without the brackets, autoconf generates a garbled combination of the code for `AC_CHECK_CACHE` and `AC_PATH_PROGS_FEATURE_CHECK` instead of properly nesting the two, I'm guessing some internal detail of how they were defined made it so that it worked by chance before.

**Comment by akobel** [comment]
Confirmed, that solves the problem.

**Comment by robol** [comment]
Great, thanks for reporting this. I will test it and see if it works for me as well.

**Comment by robol** [comment]
I pushed the change, let me know if you encounter further problems.
